# Generated by Django 5.2.1 on 2025-06-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="html_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
