# Generated by Django 5.2.1 on 2025-06-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_question_html_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="allow_na",
            field=models.BooleanField(default=False),
        ),
    ]
