# Generated by Django 5.2.1 on 2025-06-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_question_allow_na"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="answer",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answer",
            name="level",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
