# Generated by Django 5.2.1 on 2025-06-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_answer_is_submitted_remove_answer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
