# Generated by Django 5.2.1 on 2025-06-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_answer_is_submitted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="is_submitted",
        ),
        migrations.AddField(
            model_name="questionnairesubmission",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
