# Generated by Django 5.2.1 on 2025-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_answer_is_submitted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objective",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
    ]
