# Generated by Django 5.2.1 on 2025-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_objective_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="objective",
            name="phase",
            field=models.IntegerField(
                choices=[
                    (1, "Phase 1"),
                    (2, "Phase 2"),
                    (3, "Phase 3"),
                    (4, "Phase 4"),
                    (5, "Phase 5"),
                ],
                default=1,
            ),
        ),
    ]
